### ISSUE TITLE
browser.runtime.Port incorrect.

### ISSUE THREAD

**Issue by MicahZoltu** [jsmnbom/definitelytyped-firefox-webext-browser#19]
```typescript
    interface Port {
        name: string;
        disconnect: () => void;
        onDisconnect: events.Event;
        onMessage: events.Event;
        postMessage: (message: object) => void;
        /** This property will **only** be present on ports passed to onConnect/onConnectExternal listeners. */
        sender?: MessageSender;
    }
```

I believe that `onMessage` should be of type `WebExtEvent<(object: any) => void>` based on the documentation on MDN: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/Port#Type

I believe that `onDisconnect` also should be `WebExtEvent<() => void>` based on that same documentation and inspecting the `Port` object in Firefox (it has the same shape as `onMessage`).

**Comment by jsmnbom** [comment]
yes, `onMessage` and `onDisconnect` should indeed be `WebExtEvent`s. Thanks a lot for the report :)
