### ISSUE TITLE
Many async functions unnecessarily have `| undefined` in their Promise return types

### ISSUE THREAD

**Issue by josh-berry** [jsmnbom/definitelytyped-firefox-webext-browser#21]
Some (but not all) async functions defined in the generated typedefs have `undefined` as part of their return types when they shouldn't.

One example is browser.bookmarks.create(). [The MDN documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks/create) says it always returns a (promised) `BookmarkTreeNode`, yet [the DefinitelyTyped definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/86303f134e12cf701a3f3f5e24867c3559351ea2/types/firefox-webext-browser/index.d.ts#L4800) says it returns a `Promise<BookmarkTreeNode | undefined>`.

I think this is being generated incorrectly because the [Firefox schema definition](https://hg.mozilla.org/mozilla-unified/file/tip/browser/components/extensions/schemas/bookmarks.json#l302) says the callback parameter is optional, and you are taking that to mean the callback may receive `undefined`, when it really means the callback parameter itself can be omitted (indeed, MDN doesn't even show the callback parameter at all).

Some other examples of this include other bookmarks operations such as `move()` and `update()`, and window operations such as `browser.windows.create()`.

----------

Also, I'm not sure if this is related or a separate issue entirely, but it seems like some of the `browser.sessions` functions take mandatory callbacks when they shouldn't; for example [browser.sessions.getRecentlyClosed()](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/86303f134e12cf701a3f3f5e24867c3559351ea2/types/firefox-webext-browser/index.d.ts#L6791). This makes it very hard to use the Promise versions of these APIs correctly.

**Comment by jsmnbom** [comment]
Does `Promise<something | undefined>` even ever get returned by the firefox? I would assume not?

**Comment by josh-berry** [comment]
I'm honestly not sure. The bookmarks APIs at least will reject the promise with an error message if an item can't be found, so there's no reason they would ever return `undefined`. But I haven't looked at the other APIs recently. If they are consistent with bookmarks, then I doubt it, but I would recommend double-checking on MDN just to be safe.

**Comment by jsmnbom** [comment]
Okay after looking through most of the functions in question on MDN, it looks like none of them would ever return `undefined`.
