### ISSUE TITLE
Function parameters as additional types

### ISSUE THREAD

**Issue by stoically** [jsmnbom/definitelytyped-firefox-webext-browser#31]
I'm working on types for [`webextensions-api-fake`](https://github.com/stoically/webextensions-api-fake), and it would be very helpful if `firefox-webext-browser` would make function parameters additional types, so I could use them to correctly type my fake functions. E.g. [here](https://github.com/stoically/webextensions-api-fake/blob/5dd7e795d0a07101826390fb036b938ec7c73f45/src/index.d.ts#L42) I'd need the [`createProperties`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/58c168c373aeb406972af7fdcdad2476abb9ae55/types/firefox-webext-browser/index.d.ts#L6182-L6241) as type. I'll look into adjusting the converter to do so, but wanted to open the issue just in case you have suggestions on how to do it in a sane way or maybe even objections against doing it at all? Thanks!

Oh, and btw, is there a reason that some of the additionally generated types are prefixed with an underscore?

**Comment by jsmnbom** [comment]
Hmm, I don't see why this would be possible. But since it's so long time ago that i wrote the mess of code that is the converter, I'm afraid i won't be of too much help. 

And if I remember correctly anything prefixed with an underscore is generated by the converter and the type doesn't show up in the actual schemas, whereas all the types that don't have a prefix are described somewhere in the schemas.

**Comment by stoically** [comment]
Thanks for looking into it and the explanation.

> Hmm, I don't see why this would be possible. 

E.g. in my temporary containers add-on I needed [theses changes](https://github.com/stoically/DefinitelyTyped/commit/c8acf0151c987e4a2717a4278d6aa76fc969b57f) in order to be able to [declare valid listener functions](https://github.com/stoically/temporary-containers/blob/fcfb73cbee6855bd4a6b1bd58ea45f62af55b236/src/background/request.ts#L68) when adding event listeners. Without that I could need to copy & paste the whole listeners arguments.

**Comment by jsmnbom** [comment]
Oh i'm so sorry. I originally meant to write "I don't see why this *wouldn't* be possible". It is definitely possible to do. Shouldn't be *too* difficult either. It's just that, i don't currently have the time to dedicate to re-understanding how the mess of code works. I'd totally be open to PRs if you wanted to give it a try tho.
If you want to give it a try, i recommend trying to start with a single schema with as few elements as possible (ofc removing the overrides in index.ts) and debugging the code with a lot of breakpoints to follow the code around.

**Comment by stoically** [comment]
@jsmnbom Oh, thanks a lot for implementing this!

**Comment by jsmnbom** [comment]
You're welcome :) I hope the fix is okay, dispite not being exactly like https://github.com/stoically/DefinitelyTyped/commit/c8acf0151c987e4a2717a4278d6aa76fc969b57f

**Comment by stoically** [comment]
Yeah, for me it works. The reasoning for the leading `_` because parameters aren't part of the schema makes sense as well.
