### ISSUE TITLE
browser.alarms.get return value can resolve to `undefined`

### ISSUE THREAD

**Issue by peterholak** [jsmnbom/definitelytyped-firefox-webext-browser#35]
The return type of `browser.alarms.get` should be `Promise<Alarm | undefined>`, see https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/alarms/get

**Comment by jsmnbom** [comment]
Okay seems like i missed that completely in #21. I'm gonna try and fix this soon :)
Do you know if there are any other functions that return a `Promise<T | undefined>`?

**Comment by peterholak** [comment]
I don't know about any other ones, I only reported what I encountered myself. I can look at other similar `get` functions to see if there are similar cases.

**Comment by jsmnbom** [comment]
Alright, doesn't seem like there's any more, but I did find some other issues. Will try and PR definitely typed soon :)
