### ISSUE TITLE
Way to use with your own Experimental API for Firefox

### ISSUE THREAD

**Issue by lukaszpolowczyk** [jsmnbom/definitelytyped-firefox-webext-browser#38]
Own WebExtensions API convert from schema.json to globa.d.ts problem:
https://stackoverflow.com/q/64732933/873307
Can you help?

**Comment by jsmnbom** [comment]
I don't have time to provide in depth help with stuff like that, sorry!
It should however be possible to reuse a lot of the code here to do it.
