### ISSUE TITLE
Callback type - how to use in a separate function?

### ISSUE THREAD

**Issue by lukaszpolowczyk** [jsmnbom/definitelytyped-firefox-webext-browser#42]
I have this code, and it has types for callback:

![obraz](https://user-images.githubusercontent.com/16800535/146250668-5aa5d5d5-3c84-473b-ad4c-372331c020fc.png)

But when I want to keep the callback as a separate function, I don't know how to set the types for it:
![obraz](https://user-images.githubusercontent.com/16800535/146250875-d3ca78d8-99c9-484d-b9a9-bb6af94451e3.png)

How to set types for this function?
I tried for example like this:
```javascript
/** @type {browser.runtime.onMessage} */
```
...but it doesn't work.

I know this question is more about TypeScript/JSDoc, but it's also a question of how the type file is prepared. Maybe it needs to be generated differently?

For example, for the `idb` library, it is added like this:
```javascript
/** @type {idb.OpenDBCallbacks["upgrade"]} */
function upgradeCb (db, oldVersion, newVersion, transaction) {
}
```

**Comment by jsmnbom** [comment]
Uhh, I have no clue, sorry :/
I've only used this types with typescript and the ```/** @type {} */``` stuff that you're doing doesn't seem to be typescript at all.

But if you are in fact using typescript then you can either put the function directly in the call and typescript will infer it.
```ts
browser.runtime.onMessage.addListener((message: MyMessageType, sender, sendResponse) => {
    ...
});
```

Or if that's not an option then you can either look in [the type file](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/fbb677e41830566b714ab656ecfe656060391af2/types/firefox-webext-browser/index.d.ts#L4093) and find out that sender should be `browser.runtime.MessageSender`.

Or alternatively infer it from the event using something like this:

```ts
type EventCallbackType<T> = T extends WebExtEvent<infer T> ? T : never 

const handleMessage: EventCallbackType<typeof browser.runtime.onMessage> = (message, sender, sendResponse) => {
    ...
};

browser.runtime.onMessage.addListener(handleMessage)
```
