### ISSUE TITLE
Scripting API in Firefox 101

### ISSUE THREAD

**Issue by Juraj-Masiar** [jsmnbom/definitelytyped-firefox-webext-browser#44]
Hello,
Firefox 101 added Scripting API - this is the new API in the MV3 that replaced `tabs.executeScript`:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/scripting
Could you regenerate the types to include it?
**Big THANK YOU for making these types definitions!**

BTW, today the brand new ESR 102 starts it's journey:
https://wiki.mozilla.org/Release_Management/Calendar

**Comment by jsmnbom** [comment]
I will hopefully get around to this shortly. Sorry for the absolute huge wait. I'd honestly kinda forgotten about this repo. It's on my todo!
